<?php
 /**
  * @file models_nav.module.
  */

/**
 * Implements hook_block_info().
 */
function models_nav_block_info() {
  $blocks['event_nav'] = array(
    'info' => t('NAV: left hand side in event menu'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function models_nav_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'event_nav':
      $block['subject'] = t('Event Nav');
      $block['content'] = theme('block_event_nav');
    break;
  }
  return $block;
}

/**
 * Implements of hook_theme().
 */
function models_nav_theme() {
  return array (
    'block_event_nav' => array(
      'template' => 'templates/block-event-nav',
    ),
    'my_nav' => array(
      'template' => 'templates/my-nav',
    ),
    'social_nav' => array(
      'template' => 'templates/social-nav',
    ),
    'custom_nav' => array(
      'template' => 'templates/custom-nav',
    ),
  );
}

/**
 * Template preprocess for Event Nav.
 */
function template_preprocess_block_event_nav(&$vars) {
  drupal_add_js(drupal_get_path('module', 'models_nav') . '/js/models_nav.js');
  $nid = 90;
  $agenda = l(t('Agenda Builder'), 'agenda/' . $nid . '/create');
  $vars['links'] = '<li>' . $agenda . '<span class="triangle"></span></a></li>
    <li><a href="#">link item one<span class="triangle"></span></a></li>
    <li><a href="#">link item one<span class="triangle"></span></a></li>
    <li><a href="#">link item one<span class="triangle"></span></a></li>
    <li><a href="#">link item one<span class="triangle"></span></a></li>';

  $vars['links'] = '<li>' . $agenda . '</a></li>
    <li><a href="#">link item one</a></li>
    <li><a href="#">link item one</a></li>
    <li><a href="#">link item one</a></li>
    <li><a href="#">link item one</a></li>';
}

/**
 * Template preprocess for Custom Job Nav.
 */
function template_preprocess_my_nav(&$vars) {
  $nw = entity_metadata_wrapper('node', arg(1));
  if ($nw->field_hb_users->value()) {
    $reqs = '(' . sizeof($nw->field_hb_users->value()) . ')';
  }
  else {
    $reqs = FALSE;
  }

  $nav  = '<ul>';
  $nav .= '<li>' . l(t('View'), 'node/' . arg(1), array('attributes' => array('class' => array('')))) . '</li>';
  $nav .= '<li>' . l(t('Edit'), 'job/' . arg(1) . '/edit', array('attributes' => array('class' => array('')))) . '</li>';
  $nav .= '<li>' . l(t('Photos'), 'job/' . arg(1) . '/photos', array('attributes' => array('class' => array('')))) . '</li>';
  $nav .= '<li>' . l(t('Requests') . ' ' . $reqs, 'job/' . arg(1) . '/requests', array('attributes' => array('class' => array('')))) . '</li>';
  $nav .= '<li>' . l(t('Feedback'), 'job/' . arg(1) . '/feedback', array('attributes' => array('class' => array('')))) . '</li>';
  $nav .= '</ul>';
  $vars['my_nav'] = $nav;
}

/**
 * Template preprocess for Socal Nav.
 */
function template_preprocess_social_nav(&$vars) {
  global $user;
  $info = array();
  $info[] = l(t('TCs'), 'terms-and-condtions');
  $info[] = l(t('Contact'), 'contact');
  $info[] = l(t('About'), 'about');
  // $info[] = l(t('Sign Up / Sign In'), 'user/login');

  $login = array();
  $login[] = l('<span class="fa fa-envelope"></span> <span class="sr-only">' . t('Contact') . '</span>', '/', array('html' => TRUE, 'attributes' => array('class' => array('social-icon'))));
  $login[] = l('<span class="fa fa-facebook"></span> <span class="sr-only">' . t('Facebook') . '</span>', '/', array('html' => TRUE, 'attributes' => array('class' => array('social-icon'))));
  $login[] = l('<span class="fa fa-twitter"></span> <span class="sr-only">' . t('Twitter') . '</span>', '/', array('html' => TRUE, 'attributes' => array('class' => array('social-icon'))));
  $login[] = l('<span class="fa fa-instagram"></span> <span class="sr-only">' . t('Instagram') . '</span>', '/', array('html' => TRUE, 'attributes' => array('class' => array('social-icon'))));
  $login[] = l('<span class="fa fa-pinterest"></span> <span class="sr-only">' . t('Pinterest') . '</span>', '/', array('html' => TRUE, 'attributes' => array('class' => array('social-icon'))));
  $login[] = l('<span class="fa fa-google"></span> <span class="sr-only">' . t('Google') . '</span>', '/', array('html' => TRUE, 'attributes' => array('class' => array('social-icon'))));
  $login[] = $user->uid == 0 ? l(t('Sign Up / Sign In'), 'user/login') : FALSE;

  $links = '<ul class="social-icons-nav pull-right">';
  foreach ($login as $key => $value) {
    $links .= '<li>' . $value . '</li>';
  }
  $links .= '</ul>';

  $links_left = '<ul class="info-nav pull-left">';
  foreach ($info as $key => $value) {
    $links_left .= '<li>' . $value . '</li>';
  }
  $links_left .= '</ul>';

  $vars['links_right'] = '<nav role="navigation">' . $links . '</nav>';
  $vars['links_left'] = '<nav role="navigation">' . $links_left . '</nav>';
}

/**
 * Template preprocess for Custom Nav.
 */
function template_preprocess_custom_nav(&$vars) {
  global $user;
  $uw = entity_metadata_wrapper('user', $user);

  // $active_link = arg(0) == 'user' && arg(1) == $uw->getIdentifier() ? 'active' : false;
  // $link = l($pic, 'user', array('html' => true, 'attributes'=>array('class'=>array('my-menu-link'))));

  // // $created_task_count = views_get_view_result('my_stuffs', 'page');
  // // $created_task_count_badge = sizeof($created_task_count) ? ' <span class="badge">'.sizeof($created_task_count).'</span>' : false;

  // // $assigned_task_count = views_get_view_result('my_stuffs', 'page_4');
  // // $assigned_task_count_badge = sizeof($assigned_task_count) ? ' <span class="badge">'.sizeof($assigned_task_count).'</span>' : false;

  // // $requested_task_count = views_get_view_result('my_stuffs', 'page_1');
  // // $requested_task_count_badge = sizeof($requested_task_count) ? ' <span class="badge">'.sizeof($requested_task_count).'</span>' : false;


  $type = field_info_field('field_hb_bt');
  $options = list_allowed_values($type);
  $active_beauty_menu = '<div class="my-menu-dd">';
  $active_beauty_menu .= '<ul>';
  foreach ($options as $key => $value) {
    $active_beauty_menu .= '<li>' . l($value, 'job-search/type/beauty/beauty-treatment/'.$value) . '</li>';
  }
  $active_beauty_menu .= '</ul>';

  $active_beauty = strpos(current_path(), 'job-search/type/beauty') !== FALSE ? 'active' : FALSE;
  $links = '<li class="first leaf a-dd-wide a-dd ' . $active_beauty . '">' . l('Beauty', 'job-search/type/beauty') . $active_beauty_menu . '</li>';



  $type = field_info_field('field_hb_ht');
  $options = list_allowed_values($type);
  $active_hair_menu = '<div class="my-menu-dd">';
  $active_hair_menu .= '<ul>';
  foreach ($options as $key => $value) {
    $active_hair_menu .= '<li>' . l($value, 'job-search/type/hair/hair-treatment/'.$value) . '</li>';
  }
  $active_hair_menu .= '</ul>';

  $active_hair_menu .= '</div>';

  $active_hair = strpos(current_path(), 'job-search/type/hair') !== FALSE ? 'active' : FALSE;
  $links .= '<li class="leaf a-dd-wide a-dd ' . $active_hair . '">' . l('Hair', 'job-search/type/hair') . $active_hair_menu . '</li>';

  $active_msgs = current_path() == 'messages' ? 'active' : FALSE;
  $links .= '<li class="leaf ' . $active_msgs . '">' . l('Messages', 'messages') . '</li>';

  $active_msgs = current_path() == 'messages3' ? 'active' : FALSE;
  $links .= '<li class="leaf ' . $active_msgs . '">' . l('Notifications', 'messages') . '</li>';

  $active_user_menu = '<div class="my-menu-dd">';
  $active_user_menu .=
  '<ul>
    <li>
      '.l(t('Feedback'), 'feedback', array('html' => true)).'
    </li>
    <li>
      '.l(t('Edit Profile'), 'user/'.$user->uid.'/edit').'
    </li>
    <li>
      '.l(t('<i class="fa fa-sign-out"></i> Logout'), 'user/logout', array('html' => true)).'
    </li>
  </ul>';
  $active_user_menu .= '</div>';
  $mypic = $uw->value()->picture;
  if($mypic){
    $pic = '<div class="my-image img-circle">'.theme('image_style', array('style_name' => 'profile', 'path'=>$uw->value()->picture->uri, 'attributes' => array('class' => array('img-circle')))).'</div>';
  } else {
    $pic = '<div class="my-image img-circle">'.theme('image_style', array('style_name' => 'profile', 'path'=>'public://pictures/picture-default.png', 'attributes' => array('class'=>array('img-circle')))).'</div>';
  }

  $active_msgs = current_path() == 'user' ? 'active' : FALSE;
  $links .= '<li class="last leaf a-dd ' . $active_msgs . '">' .
  l('<span>Owen</span>' . $pic, 'user', array('html' => TRUE)) . $active_user_menu . '</li>';

  $vars['links'] = $links;

  // $variables['my_menu'] =
  //   '<ul class="menu nav navbar-nav my-menu">
  //     <li class="first leaf '.$active_link.'">
  //       '.$link.$active_menu.'
  //     </li>
  //   </ul>';
}

