<?php
/**
 * @file models_imgs.module.
 * Handle image uploads from dropzonejs.
 */

/**
 * Implements hook_menu().
 */
function models_imgs_menu() {
  $items['job/%/photos'] = array(
    'title' => 'Photos',
    'page callback' => 'models_imgs_jobs_page',
    // 'page arguments' =>  array('models_forms_create_form', 2),
    'access callback' => 'user_is_logged_in',
    'file' => 'models_imgs.jobs.inc',
  );
  $items['file-dz-upload'] = array(
    'title' => 'Photos',
    'page callback' => 'models_imgs_upload_page',
    'access callback' => 'user_is_logged_in',
    'file' => 'models_imgs.uploader.inc',
  );

  return $items;
}

/**
 * Implements of hook_theme().
 */
function models_imgs_theme() {
  return array (
    'dropzone_for_job' => array(
      'template' => 'templates/dropzone-for-job',
    ),
  );
}

/**
 * Template preprocess for Job Dropzone image uploader.
 */
function template_preprocess_dropzone_for_job(&$vars) {
  // drupal_add_js(drupal_get_path('module', 'models_nav') . '/js/models_nav.js');
}
